stages:
  - test
  - deploy

build:
  stage: test
  image: python:3.7-slim-buster
  script:
    - apt-get update
    - apt-get install -y --no-install-recommends libglib2.0-0 iproute2 curl
    - python -m pip install --upgrade pip
    - python -m pip install -r ./build_requirements.txt
    - python -m pytest ./skabenclient
    - python -m flake8 ./skabenclient

deploy:
  stage: deploy
  variables:
    TOKEN: $GEMFURY_PUSH_TOKEN
  script:
    - echo "Deploy to gemfury.io PyPi"
    - ./deploy_to_repo.sh
  when: manual
  only:
    - master