image: python:3.8-alpine3.11

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script: python3 -m pip install --upgrade pip && \ 
          python3 -m pip install -r ./build_requirements.txt && \
          apk add iproute2 curl

test:
  stage: test
  script: python3 -m pytest ./skabenclient && \
          python3 -m flake8 ./skabenclient
