image: python3.8:alpine3.11

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script: python -m pip install --upgrade pip && \ 
          python -m pip install -r ./build_requirements.txt && \
          apt-get install -y --no-install-recommends libglib2.0-0 iproute2 curl

test:
  stage: test
  script: python -m pytest ./skabenclient && \
          python -m flake8 ./skabenclient
