stages:
  - build

build:
  stage: build
  image: python:3.8-slim-buster
  script:
    - apt-get install -y --no-install-recommends libglib2.0-0 iproute2 curl
    - python -m pip install --upgrade pip
    - python -m pip install -r ./build_requirements.txt
