stages:
  - deploy

deploy:
  stage: deploy
  image: python:3.7-slim-buster
  variables:
    TOKEN: $GEMFURY_PUSH_TOKEN
  script:
    - apt-get update
    - apt-get install -y --no-install-recommends curl
    - python -m pip install --upgrade pip
    - python -m pip install setuptools wheel
    - echo "Deploy to gemfury.io PyPi"
    - ./deploy_to_repo.sh
  when: manual
  only:
    - master
