version: "3"

services:
  skabenclient:
    build:
      context: .
    volumes:
      - .:/app
    command: >
       sh -c "pytest /app/skabenclient && \
              flake8 /app/skabenclient"
    env_file: '.env'
