version: "3"

services:
  skabenclient:
    build:
      context: .
    volumes:
      - .:/app
    command: >
       sh -c "flake8 /app/skabenclient && \
              /app/deploy_to_repo.sh"
    env_file: '.env'


#pytest /app/skabenclient && \
